export const weeklyMenuData = [
	{
		id: 0,
		name: 'Sunday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Scrambled Eggs',
				category: 'breakfast',
				ingredients: [
					{
						id: 10,
						name: 'Eggs',
						quantityGrams: 100,
						nutrition: {
							calories: 143,
							protein: 12.6,
							carbs: 0.72,
							fat: 9.5,
							saturatedFat: 3.1,
							sugar: 0.37,
							sodium: 124,
						},
					},
				],
				nutrition: {
					calories: 143,
					protein: 12.6,
					carbs: 0.72,
					fat: 9.5,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Tofu Stir-Fry',
				category: 'main',
				ingredients: [
					{
						id: 11,
						name: 'Tofu',
						quantityGrams: 200,
						nutrition: {
							calories: 144,
							protein: 15.7,
							carbs: 3.9,
							fat: 8,
							saturatedFat: 1.2,
							sugar: 1.9,
							sodium: 9,
						},
					},
				],
				nutrition: {
					calories: 288,
					protein: 31.4,
					carbs: 7.8,
					fat: 16,
				},
			},
			{
				id: 3,
				time: { hours: 19, minutes: 0 },
				name: 'Almonds',
				category: 'snacks',
				ingredients: [
					{
						id: 12,
						name: 'Almonds',
						quantityGrams: 30,
						nutrition: {
							calories: 173,
							protein: 6.1,
							carbs: 5.6,
							fat: 15.6,
							saturatedFat: 1.1,
							sugar: 1.4,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 51.9,
					protein: 1.83,
					carbs: 1.68,
					fat: 4.68,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 1700,
				to: 1900,
			},
			protein: 30,
			carbs: 40,
			fat: 30,
		},
	},
	{
		id: 1,
		name: 'Monday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Oatmeal with Berries',
				category: 'breakfast',
				ingredients: [
					{
						id: 6,
						name: 'Oats',
						quantityGrams: 100,
						nutrition: {
							calories: 68,
							protein: 2.4,
							carbs: 11.6,
							fat: 1.4,
							saturatedFat: 0.2,
							sugar: 0.5,
							sodium: 2,
						},
					},
					{
						id: 7,
						name: 'Mixed Berries',
						quantityGrams: 100,
						nutrition: {
							calories: 52,
							protein: 0.7,
							carbs: 14.0,
							fat: 0.3,
							saturatedFat: 0,
							sugar: 10.0,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 120,
					protein: 3.1,
					carbs: 25.6,
					fat: 1.7,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 1800,
				to: 2000,
			},
			protein: 30,
			carbs: 40,
			fat: 30,
		},
	},

	{
		id: 2,
		name: 'Tuesday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Oatmeal with Berries',
				category: 'breakfast',
				ingredients: [
					{
						id: 6,
						name: 'Oats',
						quantityGrams: 100,
						nutrition: {
							calories: 68,
							protein: 2.4,
							carbs: 11.6,
							fat: 1.4,
							saturatedFat: 0.2,
							sugar: 0.5,
							sodium: 2,
						},
					},
					{
						id: 7,
						name: 'Mixed Berries',
						quantityGrams: 100,
						nutrition: {
							calories: 52,
							protein: 0.7,
							carbs: 14.0,
							fat: 0.3,
							saturatedFat: 0,
							sugar: 10.0,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 120,
					protein: 3.1,
					carbs: 25.6,
					fat: 1.7,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Grilled Salmon',
				category: 'main',
				ingredients: [
					{
						id: 8,
						name: 'Salmon',
						quantityGrams: 150,
						nutrition: {
							calories: 206,
							protein: 22.5,
							carbs: 0,
							fat: 13.4,
							saturatedFat: 3.1,
							sugar: 0,
							sodium: 59,
						},
					},
				],
				nutrition: {
					calories: 309,
					protein: 33.75,
					carbs: 0,
					fat: 20.1,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 1700,
				to: 1900,
			},
			protein: 25,
			carbs: 45,
			fat: 30,
		},
	},
	{
		id: 3,
		name: 'Wednesday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Scrambled Eggs',
				category: 'breakfast',
				ingredients: [
					{
						id: 10,
						name: 'Eggs',
						quantityGrams: 100,
						nutrition: {
							calories: 143,
							protein: 12.6,
							carbs: 0.72,
							fat: 9.5,
							saturatedFat: 3.1,
							sugar: 0.37,
							sodium: 124,
						},
					},
				],
				nutrition: {
					calories: 143,
					protein: 12.6,
					carbs: 0.72,
					fat: 9.5,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Tofu Stir-Fry',
				category: 'main',
				ingredients: [
					{
						id: 11,
						name: 'Tofu',
						quantityGrams: 200,
						nutrition: {
							calories: 144,
							protein: 15.7,
							carbs: 3.9,
							fat: 8,
							saturatedFat: 1.2,
							sugar: 1.9,
							sodium: 9,
						},
					},
				],
				nutrition: {
					calories: 288,
					protein: 31.4,
					carbs: 7.8,
					fat: 16,
				},
			},
			{
				id: 3,
				time: { hours: 19, minutes: 0 },
				name: 'Almonds',
				category: 'snacks',
				ingredients: [
					{
						id: 12,
						name: 'Almonds',
						quantityGrams: 30,
						nutrition: {
							calories: 173,
							protein: 6.1,
							carbs: 5.6,
							fat: 15.6,
							saturatedFat: 1.1,
							sugar: 1.4,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 51.9,
					protein: 1.83,
					carbs: 1.68,
					fat: 4.68,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 1800,
				to: 2000,
			},
			protein: 35,
			carbs: 35,
			fat: 30,
		},
	},
	{
		id: 4,
		name: 'Thursday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Breakfast Smoothie',
				category: 'breakfast',
				ingredients: [
					{
						id: 1,
						name: 'Banana',
						quantityGrams: 150,
						nutrition: {
							calories: 89,
							protein: 1.1,
							carbs: 22.8,
							fat: 0.3,
							saturatedFat: 0.1,
							sugar: 17.2,
							sodium: 1,
						},
					},
					{
						id: 2,
						name: 'Milk',
						quantityGrams: 200,
						nutrition: {
							calories: 60,
							protein: 3.4,
							carbs: 4.8,
							fat: 3.25,
							saturatedFat: 1.5,
							sugar: 5,
							sodium: 45,
						},
					},
				],
				nutrition: {
					calories: 223.5,
					protein: 8.7,
					carbs: 41.4,
					fat: 7.3,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Chicken Salad',
				category: 'main',
				ingredients: [
					{
						id: 3,
						name: 'Chicken Breast',
						quantityGrams: 200,
						nutrition: {
							calories: 165,
							protein: 31,
							carbs: 0,
							fat: 3.6,
							saturatedFat: 1,
							sugar: 0,
							sodium: 74,
						},
					},
					{
						id: 4,
						name: 'Lettuce',
						quantityGrams: 75,
						nutrition: {
							calories: 5,
							protein: 0.5,
							carbs: 1,
							fat: 0.1,
							saturatedFat: 0,
							sugar: 0.4,
							sodium: 3,
						},
					},
				],
				nutrition: {
					calories: 343.75,
					protein: 62.75,
					carbs: 0.75,
					fat: 7.35,
				},
			},
			{
				id: 3,
				time: { hours: 19, minutes: 0 },
				name: 'Apple',
				category: 'fruits',
				ingredients: [
					{
						id: 5,
						name: 'Apple',
						quantityGrams: 150,
						nutrition: {
							calories: 78,
							protein: 0.3,
							carbs: 20.6,
							fat: 0.2,
							saturatedFat: 0.1,
							sugar: 16.6,
							sodium: 2,
						},
					},
				],
				nutrition: {
					calories: 117,
					protein: 0.45,
					carbs: 30.9,
					fat: 0.3,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 2000,
				to: 2300,
			},
			protein: 30,
			carbs: 40,
			fat: 30,
		},
	},
	{
		id: 5,
		name: 'Friday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Oatmeal with Berries',
				category: 'breakfast',
				ingredients: [
					{
						id: 6,
						name: 'Oats',
						quantityGrams: 100,
						nutrition: {
							calories: 68,
							protein: 2.4,
							carbs: 11.6,
							fat: 1.4,
							saturatedFat: 0.2,
							sugar: 0.5,
							sodium: 2,
						},
					},
					{
						id: 7,
						name: 'Mixed Berries',
						quantityGrams: 100,
						nutrition: {
							calories: 52,
							protein: 0.7,
							carbs: 14.0,
							fat: 0.3,
							saturatedFat: 0,
							sugar: 10.0,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 120,
					protein: 3.1,
					carbs: 25.6,
					fat: 1.7,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Grilled Salmon',
				category: 'main',
				ingredients: [
					{
						id: 8,
						name: 'Salmon',
						quantityGrams: 150,
						nutrition: {
							calories: 206,
							protein: 22.5,
							carbs: 0,
							fat: 13.4,
							saturatedFat: 3.1,
							sugar: 0,
							sodium: 59,
						},
					},
				],
				nutrition: {
					calories: 309,
					protein: 33.75,
					carbs: 0,
					fat: 20.1,
				},
			},
			{
				id: 3,
				time: { hours: 19, minutes: 0 },
				name: 'Greek Yogurt',
				category: 'snacks',
				ingredients: [
					{
						id: 9,
						name: 'Greek Yogurt',
						quantityGrams: 200,
						nutrition: {
							calories: 154,
							protein: 10.2,
							carbs: 17.5,
							fat: 4.0,
							saturatedFat: 2.6,
							sugar: 16.4,
							sodium: 61,
						},
					},
				],
				nutrition: {
					calories: 308,
					protein: 20.4,
					carbs: 35,
					fat: 8,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 2400,
				to: 2600,
			},
			protein: 35,
			carbs: 35,
			fat: 30,
		},
	},
	{
		id: 6,
		name: 'Saturday',
		meals: [
			{
				id: 1,
				time: { hours: 8, minutes: 0 },
				name: 'Scrambled Eggs',
				category: 'breakfast',
				ingredients: [
					{
						id: 10,
						name: 'Eggs',
						quantityGrams: 100,
						nutrition: {
							calories: 143,
							protein: 12.6,
							carbs: 0.72,
							fat: 9.5,
							saturatedFat: 3.1,
							sugar: 0.37,
							sodium: 124,
						},
					},
				],
				nutrition: {
					calories: 143,
					protein: 12.6,
					carbs: 0.72,
					fat: 9.5,
				},
			},
			{
				id: 2,
				time: { hours: 13, minutes: 0 },
				name: 'Tofu Stir-Fry',
				category: 'main',
				ingredients: [
					{
						id: 11,
						name: 'Tofu',
						quantityGrams: 200,
						nutrition: {
							calories: 144,
							protein: 15.7,
							carbs: 3.9,
							fat: 8,
							saturatedFat: 1.2,
							sugar: 1.9,
							sodium: 9,
						},
					},
				],
				nutrition: {
					calories: 288,
					protein: 31.4,
					carbs: 7.8,
					fat: 16,
				},
			},
			{
				id: 3,
				time: { hours: 19, minutes: 0 },
				name: 'Almonds',
				category: 'snacks',
				ingredients: [
					{
						id: 12,
						name: 'Almonds',
						quantityGrams: 30,
						nutrition: {
							calories: 173,
							protein: 6.1,
							carbs: 5.6,
							fat: 15.6,
							saturatedFat: 1.1,
							sugar: 1.4,
							sodium: 1,
						},
					},
				],
				nutrition: {
					calories: 51.9,
					protein: 1.83,
					carbs: 1.68,
					fat: 4.68,
				},
			},
		],
		totalNutrition: {
			calories: 0,
			protein: 0,
			carbs: 0,
			fat: 0,
		},
		nutritionSettings: {
			calories: {
				from: 2300,
				to: 2700,
			},
			protein: 40,
			carbs: 30,
			fat: 30,
		},
	},
]
